<?php

/**
 * @file
 * Contains ice.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ice_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ice module.
    case 'help.page.ice':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ice module') . '</p>';
      return $output;

    default:
  }
}
